### ISSUE TITLE
[Feature request] Add an option to mute console logs

### ISSUE THREAD

**Issue by Finesse** [sth/karma-summary-reporter#15]
I use `karma-summary-reporter` together with [karma-spec-reporter](https://www.npmjs.com/package/karma-spec-reporter) as you suggest. Unfortunately both the reporters print messages produced by `console.log()` calls in tests, therefore the console messages are duplicated.

Since your reporter is designed for summary, I request an option to mute the live process logs to solve the duplications.

**Comment by sth** [comment]
Makes sense. I think I'll even go one step further and simply remove the console log for this reporter. Since the reporter doesn't even show any details about test failures it doesn't make much sense to show log messages and similar output.

As you say, it is recommended to use a second reporter to see all the details. That reporter will usually show all the messages and duplicating them isn't useful.

**Comment by Finesse** [comment]
Thank you! Looking forward for an NPM release

**Comment by sth** [comment]
Published as v1.9.0 :tada:
